rm(list = ls())
library(snowfall)
library(RConics)
source("./DataSet/Data.R")
source("./Models/ReMeasure_S2.R")
source("./Models/BootStrap_S2.R")
source("./Models/Batch3Only_S2.R")
source("./Models/IgnoreBatch_S2.R")
source("./Models/LSmodel_S2.R")

args <- commandArgs(trailingOnly = TRUE)
method = args[1]
n = as.numeric(args[2])
n1 = as.numeric(args[3])
n2 = as.numeric(args[4])
r1 = as.numeric(args[5])
r2 = as.numeric(args[6])
r3 = as.numeric(args[7])
a0 = as.numeric(args[8])
a1 = as.numeric(args[9])
a3 = as.numeric(args[10])
repID = as.numeric(args[11])




 method = "PairBoot"
 n = 100
 n1 = 5
 n2 = 5
 r1 = 0.5
 r2 = 0.3 
 r3 = 0.4
 a0 = 0
 a1 = 0
 a3 = 0
 repID = 2

source(paste0("./oneReplicate/oneReplicate-New-S2.R"))

savePath = paste0("./S2Data/S2-method-", method,"-repID-",repID,"-nc1-", n/2 ,"-nt2-", n/2,"-nc3-", n1, "-nt3-", n2,
                  "-r1-", r1,"-r2-", r2, "-r3-", r3, "-a0-", a0, "-a1-", a1, "-a3-", a3, ".RData")


nCPUS = 5
maxIter = 5

result1 = list()
result2 = list()
result3 = list()
result4 = list()
result5 = list()
result6 = list()
result7 = list()
result8 = list()
result9 = list()
result10 = list()
result11 = list()
result12 = list()
result13 = list()
result14 = list()
result15 = list()

if (method == "Ignore") {
  for (i in 1:ceiling(maxIter/nCPUS)){
    print(i)
    sfInit(parallel = TRUE, cpus = nCPUS)
    sfExportAll()
    sfLibrary(RConics)
    sfLibrary(MASS)
    sfLibrary(mvtnorm)
    sBegin = (i-1)*nCPUS + 1
    sEnd = min(i*nCPUS, maxIter)
    seedSeq = seq(sBegin, sEnd, by = 1)
    tmp = sfClusterApplyLB(seedSeq, oneReplicateWrap_Ignore_S2)
    sfStop()
    tmp = Filter(function(x) length(x) >= 3, tmp)
    tmp1 = lapply(tmp, function(x) x[[1]])
    tmp2 = lapply(tmp, function(x) x[[2]])
    tmp3 = lapply(tmp, function(x) x[[3]])
    tmp4 = lapply(tmp, function(x) x[[4]])
    tmp5 = lapply(tmp, function(x) x[[5]])
    tmp6 = lapply(tmp, function(x) x[[6]])
    tmp7 = lapply(tmp, function(x) x[[7]])
    tmp8 = lapply(tmp, function(x) x[[8]])
    tmp9 = lapply(tmp, function(x) x[[9]])
    tmp10 = lapply(tmp, function(x) x[[10]])
    tmp11 = lapply(tmp, function(x) x[[11]])
    tmp12 = lapply(tmp, function(x) x[[12]])
    tmp15 = lapply(tmp, function(x) x[[13]])
    result1 = c(result1, tmp1)
    result2 = c(result2, tmp2)
    result3 = c(result3, tmp3)
    result4 = c(result4, tmp4)
    result5 = c(result5, tmp5)
    result6 = c(result6, tmp6)
    result7 = c(result7, tmp7)
    result8 = c(result8, tmp8)
    result9 = c(result9, tmp9)
    result10 = c(result10, tmp10)
    result11 = c(result11, tmp11)
    result12 = c(result12, tmp12)
    result15 = c(result15, tmp15)
  }
} else if (method == "Batch3") {
  for (i in 1:ceiling(maxIter/nCPUS)){
    print(i)
    sfInit(parallel = TRUE, cpus = nCPUS)
    sfExportAll()
    sfLibrary(RConics)
    sfLibrary(MASS)
    sfLibrary(mvtnorm)
    sBegin = (i-1)*nCPUS + 1
    sEnd = min(i*nCPUS, maxIter)
    seedSeq = seq(sBegin, sEnd, by = 1)
    tmp = sfClusterApplyLB(seedSeq, oneReplicateWrap_OnlyBatch3)
    sfStop()
    tmp = Filter(function(x) length(x) >= 3, tmp)
    tmp1 = lapply(tmp, function(x) x[[1]])
    tmp2 = lapply(tmp, function(x) x[[2]])
    tmp3 = lapply(tmp, function(x) x[[3]])
    tmp4 = lapply(tmp, function(x) x[[4]])
    tmp5 = lapply(tmp, function(x) x[[5]])
    tmp6 = lapply(tmp, function(x) x[[6]])
    tmp7 = lapply(tmp, function(x) x[[7]])
    tmp8 = lapply(tmp, function(x) x[[8]])
    tmp9 = lapply(tmp, function(x) x[[9]])
    tmp10 = lapply(tmp, function(x) x[[10]])
    tmp11 = lapply(tmp, function(x) x[[11]])
    tmp12 = lapply(tmp, function(x) x[[12]])
    tmp15 = lapply(tmp, function(x) x[[13]])
    result1 = c(result1, tmp1)
    result2 = c(result2, tmp2)
    result3 = c(result3, tmp3)
    result4 = c(result4, tmp4)
    result5 = c(result5, tmp5)
    result6 = c(result6, tmp6)
    result7 = c(result7, tmp7)
    result8 = c(result8, tmp8)
    result9 = c(result9, tmp9)
    result10 = c(result10, tmp10)
    result11 = c(result11, tmp11)
    result12 = c(result12, tmp12)
    result15 = c(result15, tmp15)
  }
  
} else if (method == "ReMeasure") {
  for (i in 1:ceiling(maxIter/nCPUS)){
    print(i)
    sfInit(parallel = TRUE, cpus = nCPUS)
    sfExportAll()
    sfLibrary(RConics)
    sfLibrary(MASS)
    sfLibrary(mvtnorm)
    sBegin = (i-1)*nCPUS + 1
    sEnd = min(i*nCPUS, maxIter)
    seedSeq = seq(sBegin, sEnd, by = 1)
    tmp = sfClusterApplyLB(seedSeq, oneReplicateWrap_ReMeasure_S2)
    sfStop()
    tmp = Filter(function(x) length(x) >= 3, tmp)
    tmp1 = lapply(tmp, function(x) x[[1]])
    tmp2 = lapply(tmp, function(x) x[[2]])
    tmp3 = lapply(tmp, function(x) x[[3]])
    tmp4 = lapply(tmp, function(x) x[[4]])
    tmp5 = lapply(tmp, function(x) x[[5]])
    tmp6 = lapply(tmp, function(x) x[[6]])
    tmp7 = lapply(tmp, function(x) x[[7]])
    tmp8 = lapply(tmp, function(x) x[[8]])
    tmp9 = lapply(tmp, function(x) x[[9]])
    tmp10 = lapply(tmp, function(x) x[[10]])
    tmp11 = lapply(tmp, function(x) x[[11]])
    tmp12 = lapply(tmp, function(x) x[[12]])
    tmp15 = lapply(tmp, function(x) x[[13]])
    result1 = c(result1, tmp1)
    result2 = c(result2, tmp2)
    result3 = c(result3, tmp3)
    result4 = c(result4, tmp4)
    result5 = c(result5, tmp5)
    result6 = c(result6, tmp6)
    result7 = c(result7, tmp7)
    result8 = c(result8, tmp8)
    result9 = c(result9, tmp9)
    result10 = c(result10, tmp10)
    result11 = c(result11, tmp11)
    result12 = c(result12, tmp12)
    result15 = c(result15, tmp15)
  }
} else if (method == "ResBoot") {
  for (i in 1:ceiling(maxIter/nCPUS)){
    print(i)
    sfInit(parallel = TRUE, cpus = nCPUS)
    sfExportAll()
    sfLibrary(RConics)
    sfLibrary(MASS)
    sfLibrary(mvtnorm)
    sBegin = (i-1)*nCPUS + 1
    sEnd = min(i*nCPUS, maxIter)
    seedSeq = seq(sBegin, sEnd, by = 1)
    tmp = sfClusterApplyLB(seedSeq, oneReplicateWrap_Res_S2)
    sfStop()
    tmp = Filter(function(x) length(x) >= 3, tmp)
    tmp1 = lapply(tmp, function(x) x[[1]])
    tmp2 = lapply(tmp, function(x) x[[2]])
    tmp3 = lapply(tmp, function(x) x[[3]])
    tmp4 = lapply(tmp, function(x) x[[4]])
    tmp5 = lapply(tmp, function(x) x[[5]])
    tmp6 = lapply(tmp, function(x) x[[6]])
    tmp7 = lapply(tmp, function(x) x[[7]])
    tmp8 = lapply(tmp, function(x) x[[8]])
    tmp9 = lapply(tmp, function(x) x[[9]])
    tmp10 = lapply(tmp, function(x) x[[10]])
    tmp11 = lapply(tmp, function(x) x[[11]])
    tmp12 = lapply(tmp, function(x) x[[12]])
    tmp13 = lapply(tmp, function(x) x[[13]])
    tmp14 = lapply(tmp, function(x) x[[14]])
    result1 = c(result1, tmp1)
    result2 = c(result2, tmp2)
    result3 = c(result3, tmp3)
    result4 = c(result4, tmp4)
    result5 = c(result5, tmp5)
    result6 = c(result6, tmp6)
    result7 = c(result7, tmp7)
    result8 = c(result8, tmp8)
    result9 = c(result9, tmp9)
    result10 = c(result10, tmp10)
    result11 = c(result11, tmp11)
    result12 = c(result12, tmp12)
    result13 = c(result13, tmp13)
    result14 = c(result14, tmp14)
  }
} else if (method == "WildBoot") {
  for (i in 1:ceiling(maxIter/nCPUS)){
    print(i)
    sfInit(parallel = TRUE, cpus = nCPUS)
    sfExportAll()
    sfLibrary(RConics)
    sfLibrary(MASS)
    sfLibrary(mvtnorm)
    sBegin = (i-1)*nCPUS + 1
    sEnd = min(i*nCPUS, maxIter)
    seedSeq = seq(sBegin, sEnd, by = 1)
    tmp = sfClusterApplyLB(seedSeq, oneReplicateWrap_Wild_S2)
    sfStop()
    tmp = Filter(function(x) length(x) >= 3, tmp)
    tmp1 = lapply(tmp, function(x) x[[1]])
    tmp2 = lapply(tmp, function(x) x[[2]])
    tmp3 = lapply(tmp, function(x) x[[3]])
    tmp4 = lapply(tmp, function(x) x[[4]])
    tmp5 = lapply(tmp, function(x) x[[5]])
    tmp6 = lapply(tmp, function(x) x[[6]])
    tmp7 = lapply(tmp, function(x) x[[7]])
    tmp8 = lapply(tmp, function(x) x[[8]])
    tmp9 = lapply(tmp, function(x) x[[9]])
    tmp10 = lapply(tmp, function(x) x[[10]])
    tmp11 = lapply(tmp, function(x) x[[11]])
    tmp12 = lapply(tmp, function(x) x[[12]])
    tmp13 = lapply(tmp, function(x) x[[13]])
    tmp14 = lapply(tmp, function(x) x[[14]])
    result1 = c(result1, tmp1)
    result2 = c(result2, tmp2)
    result3 = c(result3, tmp3)
    result4 = c(result4, tmp4)
    result5 = c(result5, tmp5)
    result6 = c(result6, tmp6)
    result7 = c(result7, tmp7)
    result8 = c(result8, tmp8)
    result9 = c(result9, tmp9)
    result10 = c(result10, tmp10)
    result11 = c(result11, tmp11)
    result12 = c(result12, tmp12)
    result13 = c(result13, tmp13)
    result14 = c(result14, tmp14)
  }
} else if (method == "PairBoot") {
  for (i in 1:ceiling(maxIter/nCPUS)){
    print(i)
    sfInit(parallel = TRUE, cpus = nCPUS)
    sfExportAll()
    sfLibrary(RConics)
    sfLibrary(MASS)
    sfLibrary(mvtnorm)
    sBegin = (i-1)*nCPUS + 1
    sEnd = min(i*nCPUS, maxIter)
    seedSeq = seq(sBegin, sEnd, by = 1)
    tmp = sfClusterApplyLB(seedSeq, oneReplicateWrap_Pair_S2)
    sfStop()
    tmp = Filter(function(x) length(x) >= 3, tmp)
    tmp1 = lapply(tmp, function(x) x[[1]])
    tmp2 = lapply(tmp, function(x) x[[2]])
    tmp3 = lapply(tmp, function(x) x[[3]])
    tmp4 = lapply(tmp, function(x) x[[4]])
    tmp5 = lapply(tmp, function(x) x[[5]])
    tmp6 = lapply(tmp, function(x) x[[6]])
    tmp7 = lapply(tmp, function(x) x[[7]])
    tmp8 = lapply(tmp, function(x) x[[8]])
    tmp9 = lapply(tmp, function(x) x[[9]])
    tmp10 = lapply(tmp, function(x) x[[10]])
    tmp11 = lapply(tmp, function(x) x[[11]])
    tmp12 = lapply(tmp, function(x) x[[12]])
    tmp13 = lapply(tmp, function(x) x[[13]])
    tmp14 = lapply(tmp, function(x) x[[14]])
    result1 = c(result1, tmp1)
    result2 = c(result2, tmp2)
    result3 = c(result3, tmp3)
    result4 = c(result4, tmp4)
    result5 = c(result5, tmp5)
    result6 = c(result6, tmp6)
    result7 = c(result7, tmp7)
    result8 = c(result8, tmp8)
    result9 = c(result9, tmp9)
    result10 = c(result10, tmp10)
    result11 = c(result11, tmp11)
    result12 = c(result12, tmp12)
    result13 = c(result13, tmp13)
    result14 = c(result14, tmp14)
  }
} else if (method == "LS") {
  for (i in 1:ceiling(maxIter/nCPUS)){
    print(i)
    sfInit(parallel = TRUE, cpus = nCPUS)
    sfExportAll()
    sfLibrary(RConics)
    sfLibrary(MASS)
    sfLibrary(mvtnorm)
    sBegin = (i-1)*nCPUS + 1
    sEnd = min(i*nCPUS, maxIter)
    seedSeq = seq(sBegin, sEnd, by = 1)
    tmp = sfClusterApplyLB(seedSeq, oneReplicateWrap_LS_S2)
    sfStop()
    tmp = Filter(function(x) length(x) >= 3, tmp)
    tmp1 = lapply(tmp, function(x) x[[1]])
    tmp2 = lapply(tmp, function(x) x[[2]])
    tmp3 = lapply(tmp, function(x) x[[3]])
    tmp4 = lapply(tmp, function(x) x[[4]])
    tmp5 = lapply(tmp, function(x) x[[5]])
    tmp6 = lapply(tmp, function(x) x[[6]])
    tmp7 = lapply(tmp, function(x) x[[7]])
    tmp8 = lapply(tmp, function(x) x[[8]])
    tmp9 = lapply(tmp, function(x) x[[9]])
    tmp10 = lapply(tmp, function(x) x[[10]])
    tmp11 = lapply(tmp, function(x) x[[11]])
    tmp12 = lapply(tmp, function(x) x[[12]])
    tmp15 = lapply(tmp, function(x) x[[13]])
    result1 = c(result1, tmp1)
    result2 = c(result2, tmp2)
    result3 = c(result3, tmp3)
    result4 = c(result4, tmp4)
    result5 = c(result5, tmp5)
    result6 = c(result6, tmp6)
    result7 = c(result7, tmp7)
    result8 = c(result8, tmp8)
    result9 = c(result9, tmp9)
    result10 = c(result10, tmp10)
    result11 = c(result11, tmp11)
    result12 = c(result12, tmp12)
    result15 = c(result15, tmp15)
  }
}


Final = list("a0" = result1, "a0Var"= result2, "a1"=result3, "a3" = result4, "sigma1"=result5,
             "sigma2" = result6, "sigma3" = result7, "rho1" = result8, "rho2" = result9,
             "beta"=result10, "objVec"=result11,
             "Time" = result12, "ztest" = result13, "ztestb" = result14, "p.value" = result15)

save(Final, file = savePath)






